// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductAppService.Aggregates;

#nullable disable

namespace ProductAppService.Migrations
{
    [DbContext(typeof(ProductsDbContext))]
    partial class ProductsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductAppService.Aggregates.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "Apparel"
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "Footwear"
                        });
                });

            modelBuilder.Entity("ProductAppService.Aggregates.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("SubCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Sample product 1",
                            ImageUrl = "product1.jpg",
                            Name = "Product 1",
                            Price = 99.99m,
                            ProductCode = "P001",
                            Quantity = 50,
                            SubCategoryId = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Description = "Sample product 2",
                            ImageUrl = "product2.jpg",
                            Name = "Product 2",
                            Price = 49.99m,
                            ProductCode = "P002",
                            Quantity = 25,
                            SubCategoryId = 4
                        });
                });

            modelBuilder.Entity("ProductAppService.Aggregates.SubCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("SubCategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SubCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            SubCategoryName = "TV"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            SubCategoryName = "Mobile"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            SubCategoryName = "Refrigerator"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            SubCategoryName = "Men's Cloth"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            SubCategoryName = "Women's Cloth"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            SubCategoryName = "Men's Footwear"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            SubCategoryName = "Kid's Footwear"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
